Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.network "private_network", ip: "192.168.50.10"
  config.vm.synced_folder ".", "/vagrant/"
  config.vm.synced_folder "../data/rdf/", "/vagrant/rdf"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y puppet-common
  SHELL

 config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "."
    puppet.manifest_file  = "instfuseki.pp"
  end
 
end



